# Generated by Django 6.0 on 2026-01-06 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_property',
        ),
    ]
