# Generated by Django 6.0 on 2026-01-07 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_property',
        ),
    ]
