# Generated by Django 6.0 on 2026-01-07 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0009_tbl_propertytype'),
        ('Guest', '0010_tbl_owner'),
        ('Owner', '0004_delete_tbl_property'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_title', models.CharField(max_length=100)),
                ('property_details', models.CharField(max_length=500)),
                ('property_date', models.DateField(auto_now_add=True)),
                ('property_status', models.IntegerField(default=0)),
                ('property_photo', models.FileField(upload_to='Assets/PropertyPhotos/')),
                ('property_amount', models.CharField(max_length=50)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_owner')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
                ('propertytype_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_propertytype')),
            ],
        ),
    ]
