# Generated by Django 6.0 on 2026-01-07 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0005_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_photo', models.FileField(upload_to='Assets/GalleryPhotos/')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Owner.tbl_property')),
            ],
        ),
    ]
