from django.urls import path,include
from Admin import views
app_name="Admin"

urlpatterns = [
    path('District/',views.District,name="District"),
    path('Category/',views.Category,name="Category"),
    path('AdminReg/',views.AdminReg,name="AdminReg"),
    path('deldistrict/<int:did>',views.deldistrict,name="deldistrict"),
    path('delcategory/<int:cid>',views.delcategory,name="delcategory"),
    path('deladmin/<int:aid>',views.deladmin,name="deladmin"),
    path('editdistrict/<int:edid>',views.editdistrict,name="editdistrict"),
    path('editcategory/<int:ecid>',views.editcategory,name="editcategory"),
    path('editadmin/<int:eid>',views.editadmin,name="editadmin"),
    path('Place/',views.Place,name="Place"),
    path('editplace/<int:epid>',views.editplace,name="editplace"),
    path('delplace/<int:did>',views.delplace,name="delplace"),
    path('subcategory/',views.subcategory,name="subcategory"),
    path('editsubcategory/<int:escid>',views.editsubcategory,name="editsubcategory"),
    path('delsubcategory/<int:dsid>',views.delsubcategory,name="delsubcategory"),
    path('designation/',views.designation,name="Designation"),
    path('editdesignation/<int:eid>',views.editdesignation,name="editdesignation"),
    path('deldesignation/<int:did>',views.deldesignation,name="deldesignation"),
    path('department/',views.department,name="Department"),
    path('editdepartment/<int:eid>',views.editdepartment,name="editdepartment"),
    path('deldepartment/<int:did>',views.deldepartment,name="deldepartment"),
    path('Employee/',views.employee,name="Employee"),
    path('editemployee/<int:eid>',views.editemployee,name="editemployee"),
    path('delemployee/<int:did>',views.delemployee,name="delemployee"),
    path('Sellerlist/',views.sellerlist,name="Sellerlist"),
    path('userlist/',views.userlist,name="userlist"),
    path('acceptseller/<int:aid>/',views.acceptseller,name="acceptseller"),
    path('rejectseller/<int:rid>/',views.rejectseller,name="rejectseller"),
    path('acceptuser/<int:aid>/',views.acceptuser,name="acceptuser"),
    path('rejectuser/<int:rid>/',views.rejectuser,name="rejectuser"),
    path('Homepage/',views.Homepage,name="Homepage"),
    path('Viewcomplaint/',views.Viewcomplaint,name="Viewcomplaint"),
    path('Reply/<int:cid>/',views.Reply,name="Reply"),
    path('Ownerlist/',views.ownerlist,name="Ownerlist"),
    path('owneraccept/<int:aid>/',views.owneraccept,name="owneraccept"),
    path('ownerreject/<int:rid>/',views.ownerreject,name="ownerreject"),
    path('propertytype/',views.propertytype,name="propertytype"),
    path('delpropertytype/<int:ptid>/',views.delpropertytype,name="delpropertytype"),
    path('viewservices/',views.viewservices,name="viewservices"),
    path('acceptservice/<int:sid>/',views.acceptservice,name="acceptservice"),
    path('rejectservice/<int:sid>/',views.rejectservice,name="rejectservice"),
    path('serviceamount/<int:sid>/',views.serviceamount,name="serviceamount"),
    path('logout/',views.logout,name="logout"),
    path('editpropertytype/<int:ptid>/',views.editpropertytype,name="edipropertype"),
   
]