# Generated by Django 6.0 on 2025-12-29 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_tbl_employee'),
        ('Guest', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('user_email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('estd_date', models.CharField(max_length=50)),
                ('license_num', models.CharField(max_length=50)),
                ('owner_name', models.CharField(max_length=50)),
                ('license_proof', models.FileField(upload_to='Assets/SellerDocs/')),
                ('owner_proof', models.FileField(upload_to='Assets/SellerDocs/')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
