# Generated by Django 6.0 on 2025-12-30 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0004_tbl_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_user',
            name='place',
        ),
        migrations.DeleteModel(
            name='tbl_seller',
        ),
        migrations.DeleteModel(
            name='tbl_user',
        ),
    ]
