# Generated by Django 6.0 on 2025-12-30 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0008_tbl_employee'),
        ('Guest', '0005_remove_tbl_user_place_delete_tbl_seller_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=50)),
                ('seller_contact', models.CharField(max_length=50)),
                ('seller_email', models.CharField(max_length=50)),
                ('sellerpassword', models.CharField(max_length=50)),
                ('estd_date', models.CharField(max_length=50)),
                ('license_num', models.CharField(max_length=50)),
                ('owner_name', models.CharField(max_length=50)),
                ('license_proof', models.FileField(upload_to='Assets/SellerDocs/')),
                ('owner_proof', models.FileField(upload_to='Assets/SellerDocs/')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_gender', models.CharField(max_length=50)),
                ('user_contact', models.CharField(max_length=50)),
                ('user_email', models.CharField(max_length=50)),
                ('user_password', models.CharField(max_length=50)),
                ('user_address', models.CharField(max_length=50)),
                ('user_image', models.FileField(upload_to='Assets/UserDocs/')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
