# Generated by Django 6.0 on 2025-12-30 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0006_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_seller',
            old_name='sellerpassword',
            new_name='seller_password',
        ),
    ]
