# Generated by Django 6.0 on 2025-12-30 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0007_rename_sellerpassword_tbl_seller_seller_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_seller',
            name='seller_status',
            field=models.IntegerField(default=0),
        ),
    ]
