# Generated by Django 6.0 on 2025-12-30 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0008_tbl_seller_seller_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_user',
            name='user_status',
            field=models.IntegerField(default=0),
        ),
    ]
