# Generated by Django 6.0 on 2026-01-05 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_tbl_employee'),
        ('Guest', '0009_tbl_user_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=50)),
                ('owner_email', models.CharField(max_length=50)),
                ('owner_contact', models.CharField(max_length=50)),
                ('owner_address', models.CharField(max_length=50)),
                ('owner_photo', models.FileField(upload_to='Assets/OwnerDocs/')),
                ('owner_proof', models.FileField(upload_to='Assets/OwnerDocs/')),
                ('owner_password', models.CharField(max_length=50)),
                ('owner_status', models.IntegerField(default=0)),
                ('owner_doj', models.DateField(auto_now_add=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
