# Generated by Django 6.0 on 2026-01-14 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_tbl_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_servicerequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicerequest_title', models.CharField(max_length=50)),
                ('servicerequest_details', models.CharField(max_length=100)),
                ('servicerequest_reply', models.CharField(max_length=100, null=True)),
                ('servicerequest_date', models.DateField(auto_now_add=True)),
                ('servicerequest_time', models.TimeField(auto_now_add=True)),
                ('servicerequest_amount', models.CharField(max_length=50, null=True)),
                ('servicerequest_status', models.IntegerField(default=0)),
                ('requestid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.tbl_request')),
            ],
        ),
    ]
