# Generated by Django 6.0 on 2026-02-10 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_tbl_servicerequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_rating',
            name='ownerid',
        ),
    ]
