# Generated by Django 6.0 on 2026-02-10 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_remove_tbl_rating_ownerid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_rating',
        ),
    ]
