# Generated by Django 6.0 on 2026-02-10 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0010_tbl_owner'),
        ('Owner', '0006_tbl_gallery'),
        ('User', '0006_delete_tbl_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_content', models.CharField(max_length=100)),
                ('rating_value', models.IntegerField(default=0)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('propertyid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Owner.tbl_property')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
