# Generated by Django 6.0 on 2026-02-10 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_tbl_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_rating',
        ),
    ]
